name: CI/CD for Next.js App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: Docker 이미지 빌드
        run: |
          docker build -t my-nextjs-app .

      - name: .env 파일 생성
        run: |
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" > .env

      - name: 실행 중인 컨테이너 중지 및 삭제 (있다면)
        run: |
          docker stop my-nextjs-app || true
          docker rm my-nextjs-app || true

      - name: Docker 컨테이너 재시작
        run: |
          docker run -d \
            --name my-nextjs-app \
            --env-file .env \
            -p 3000:3000 \
            my-nextjs-app
